# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: circleci/node:16.10.0
      - image: circleci/mongo:4.4

    working_directory: ~/homebrewery
    executor: node/default

    steps:
      - checkout:
          path: ~/homebrewery

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - node/install-npm
      - node/install-packages:
          app-dir: ~/homebrewery
          cache-path: node_modules
          override-ci-command: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: circleci/node:16.10.0
      - image: circleci/mongo:4.4

    working_directory: ~/homebrewery
    parallelism: 4

    steps:
      - attach_workspace:
          at: .

      # run tests!
      - run: 
          name: Tests
          command: npm run circleci

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build