const _ = require('lodash');

module.exports = function(){

	return [
		'<style>',
		'  ',
		'  /* -----  Quick Entry ----- */',
		'  /* ------------------------ */  ',
		'  ',
		'  :root {',
		'  	--zoom:0.5;			/* 1=100%, 2=200%, etc 			*/',
		'  	--book:none;  		/* initial=offset first page, 	*/',
		'  						/* none=no offset of first page */',
		'  }',
		'  ',
		'  /* -----  Setting up page spread ----- */',
		'  /* ----------------------------------- */',
		'    ',
		'  .brewRenderer {',
		'  	transform:scale(calc(1/var(--zoom)));',
		'   	transform-origin: 0% 0%;',
		'  	overflow: unset !important;',
		'  }',
		'  ',
		'  .pages {',
		'    display:grid;',
		'  	width:calc(100%*var(--zoom));',
		'  	height:calc(98%*var(--zoom));',
		'  	overflow-y: scroll;',
		'  	margin-top:0px !important;',
		'  	padding: 5mm;',
		'  	grid-template-columns: repeat(auto-fill, 365px);',
		'  	column-gap:20px;',
		'  	row-gap:20px;',
		'  	justify-content: center;',
		'  }',
		'  ',
		'  .pages:before {',
		'  	content: \'\';',
		'  	display:var(--book);',
		'  }',
		'  ',
		'  /* -----  Hiding footer graphic, and',
		'  starting page numbering from 4th page',
		'  so that the title and next few pages ',
		'  aren\'t considered a "page" ----- */',
		'  ',
		'  /* ---------------------------------------- */',
		'  ',
		'  .phb::after {',
		'  	display:none;',
		'  }',
		'  ',
		'  .phb#p4 {',
		'  	counter-reset:phb-page-numbers;',
		'  }',
		'  ',
		'  ',
		'  /* ----- Card Template ----- */',
		'  ',
		'  ',
		'  .phb {',
		'  	width: 67mm;',
		'  	height: 89mm;',
		'  	border: 1px solid black;',
		'  	border-radius:21px',
		'  }',
		'  ',
		'  .phb h1 {',
		'  	font-size: 16px;',
		'  	margin-bottom: 0px;',
		'  }',
		'  ',
		'  .phb h2 {',
		'  	font-family: \'Open Sans\',sans-serif;',
		'  	font-size: 8px;',
		'  	color: black;',
		'  	font-style: italic;',
		'  	padding-bottom: 3px;',
		'  	border-bottom: 2px solid #cc3333;',
		'  }',
		'  ',
		'  .phb:nth-of-type(2n+1) {  		',
		'  	background-image: url(https://i.imgur.com/iNJH8j9.png) !important;',
		'  	background-size: cover;',
		'  	background-color: #7f0000;',
		'  }',
		'  ',
		'  .phb:nth-of-type(2n+1):before {',
		'  	content: \'\';',
		'  }',
		'',
		'  .phb:nth-of-type(2n) {',
		'  	padding: 3mm 5mm 3mm 5mm;',
		'  } ',
		'  ',
		'  .phb:nth-of-type(2n):before {',
		'    content: \'\';',
		'    position:absolute;',
		'    width:100%;',
		'    height:100%;',
		'    top:0;',
		'    left:0;',
		'    z-index:300;',
		'    box-shadow: 0 0 15px 5px #0000009f inset;',
		'  }',
		'  ',
		'  .phb img {',
		'  	width: 35%;',
		'  	padding-top: 5px;',
		'    margin: auto;',
		'    display: block;',
		'  	mix-blend-mode:darken;',
		'  }',
		'  ',
		'  .phb p {',
		'  	padding-bottom: 0.4em;',
		'  	font-size: 7px;',
		'  }',
		'',
		'  .phb .centered {',
		'    margin: auto;',
		'    display: block;',
		'  	text-align: center;',
		'  	mix-blend-mode:darken;',
		'  }',
		'  ',
		'  .phb .caption {',
		'  	margin-top: 5px;',
		'  	font-style: italic;',
		'  	font-size: 7px;',
		'  	font-weight: normal;',
		'  	text-align: center;',
		'  	display: block;',
		'  	text-indent: 0;',
		'  	line-height: 1em;',
		'  }',
		'  .phb .image-credits {',
		'  	position: absolute;',
		'  	right: 20px;',
		'  	bottom: 15px;',
		'  	font-style: italic;',
		'  	font-size: 0.75em;',
		'  }',
		'  ',
		'  .phb hr + blockquote {',
		'  	padding-top: 2px;',
		'  	padding-bottom: 2px;',
		'  }',
		'  ',
		'  .phb blockquote p {',
		'  	font-size: 9px;',
		'  	line-height: 1em;',
		'  }',
		'  ',
		'</style>',
		'  ',
		'\\page',
		'  ',
		'  # Dagger of Ineptitude',
		'  ## Cursed item; -1 Dagger',
		'  1D4-1; 1D+1 when cleansed',
		'  <img src=\'https://i.imgur.com/U5X53td.jpeg\'></img>',
		'  <span class="caption">This dagger is a danger to everyone but the intended target.</span>',
		'___',
		'>This dagger inflicts a **-1** modifier to both attack and damage rolls. Additionally, on a Natural 1 attack roll, the dagger slips from the wielder\'s grasp. Roll 1D6, on a 1 the former wielder takes 1D4 piercing damage as the blade embeds itself in their foot.  ',
		'>As a cursed item, the dagger may not be discarded and no other weapons wielded until the curse is lifted via **Remove Curse**; at which time the dagger becomes a normal **+1 Dagger**.',
		'  ',
		'  <span class=\'image-credits\'>https://i.imgur.com/U5X53td.jpeg</span>',
	].join('\n')
};

